server:
  port: 8885

spring:
  application:
    name: pika-redis-service
  devtools:
    livereload:
      port: 35732
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000   # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-active: 100   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 0       # 连接池中的最小空闲连接




