server:
  port: 8883

spring:
  # 应用名
  application:
    name: demo-database-mongodb
  devtools:
    livereload:
      port: 35732
  # 注册到nacos注册中心
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/test

# nacos配置
management:
  endpoints:
    web:
      exposure:
        include: "*"




